services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/ma_db2
      - FRONTEND_URL=http://localhost:5173
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ma_db2
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data: